name: Semgrep SAST
on:
  push:
    branches: [ master, main ]
  pull_request:

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Semgrep (OWASP Top 10)
        id: semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/owasp-top-ten"
          generateSarif: true
        env:
          SEMGREP_ENABLE_VERSION_CHECK: "0"
        continue-on-error: true   # ← don't fail the job even if findings

      - name: Upload Semgrep SARIF
        if: ${{ always() }}        # ← still upload even if step above flagged
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-sarif
          path: semgrep.sarif
