name: Semgrep SAST

on:
  push:
    branches: [ master, main ]
  pull_request:

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Semgrep (OWASP Top 10)
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/owasp-top-ten"
          generateSarif: true
        env:
          SEMGREP_ENABLE_VERSION_CHECK: "0"

      - name: Upload Semgrep SARIF
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-sarif
          path: semgrep.sarif
