name: Semgrep SAST
on:
  push:
    branches: [ master, main ]
  pull_request:

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Semgrep (OWASP Top 10)
        id: semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/owasp-top-ten"
          # Write SARIF to a file we can upload
          args: "--sarif --output semgrep.sarif"
        env:
          SEMGREP_ENABLE_VERSION_CHECK: "0"
        continue-on-error: true   # findings won't fail the job

      - name: Show files (debug)
        run: ls -la

      - name: Upload Semgrep SARIF
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-sarif
          path: semgrep.sarif

