# .github/workflows/semgrep.yml
name: Semgrep SAST
on:
  push: { branches: [ master, main ] }
  pull_request:

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install the CLI so we control output location/format
      - name: Install Semgrep
        run: |
          python3 -m pip install --upgrade pip
          pip install semgrep

      # Use the OWASP Top-10 ruleset; write SARIF; never fail CI on findings
      - name: Run Semgrep (OWASP Top 10) → SARIF
        run: semgrep --config p/owasp-top-ten --sarif -o semgrep.sarif . || true

      # Keep evidence as a downloadable artifact
      - name: Upload Semgrep SARIF
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-sarif
          path: semgrep.sarif
